name: Main CI

on:
  push:
    branches:
        - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write


jobs:
  main_job:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} #automated, not necesary to make a secret manually

      - name: Build and push to GHCR taskflow-backend Docker Image
        working-directory: ./backend
        run: |

          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)

          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/taskflow-backend"

          docker build \
          -t ${IMAGE_NAME}:latest \
          -t ${IMAGE_NAME}:${SHORT_SHA} \
          .

          docker push ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:${SHORT_SHA}

      - name: Build and push to GHCR taskflow-frontend Docker Image
        working-directory: ./frontend
        run: |

          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)

          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/taskflow-frontend"

          docker build \
          -t ${IMAGE_NAME}:latest \
          -t ${IMAGE_NAME}:${SHORT_SHA} \
          .

          docker push ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:${SHORT_SHA}


        
